### ISSUE TITLE
undefined response.statusCode

### ISSUE THREAD

**Issue by aanev** [jmreyes/passport-google-id-token#4]
/my_app/node_modules/passport-google-id-token/lib/passport-google-id-token/strategy.js:21
    if(err && response.statusCode !== 200) {
                      ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/my_app/node_modules/passport-google-id-token/lib/passport-google-id-token/strategy.js:21:23)
    at self.callback (/my_app/node_modules/passport-google-id-token/node_modules/request/request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/my_app/node_modules/passport-google-id-token/node_modules/request/request.js:867:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)

**Comment by jmreyes** [comment]
Thanks for the report! I've been a bit busy lately, will fix it ASAP. I guess you already know that you can pass your own method to handle certificate requests as you see fit, useful in the meantime if this is giving you trouble.
